name: Blondie-Auto-Scanner

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Discovery new channels
        run: python discovery_cache.py

      - name: Run scanner script
        run: python scanner.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Blondie-Bot"
          git config --global user.email "bot@stella.ai"

          # Добавляем и каналы, и конфиги
          git add telegram_channels.json live_configs.txt
          
          if git diff --cached --quiet; then
            echo "✨ Изменений не обнаружено."
          else
            git commit -m "👱‍♀️ Stella: Авто‑обновление базы каналов и конфигов ✨"
            git push origin HEAD:main
          fi